#!/bin/bash

echo "🚀 QuizMaster Backend - Vercel Database Setup"
echo "=============================================="
echo ""
echo "Your backend is deployed and Django is running! ✅"
echo "But it's getting 500 errors because there's NO DATABASE configured."
echo ""
echo "📋 Current Status:"
echo "  ✅ Backend URL: https://quiz-master-app-swart.vercel.app"
echo "  ✅ Django is running (root endpoint works)"
echo "  ❌ No database = 500 errors on all data endpoints"
echo ""
echo "🔧 You have 3 options to fix this:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: Vercel Postgres (RECOMMENDED - Easiest)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click your backend project"
echo "3. Click 'Storage' tab"
echo "4. Click 'Create Database'"
echo "5. Select 'Postgres'"
echo "6. Name it: quizmaster-db"
echo "7. Click 'Create'"
echo "8. Vercel automatically adds DATABASE_URL ✨"
echo "9. Go to 'Settings' → 'Environment Variables'"
echo "10. Make sure these exist:"
echo "    - POSTGRES_URL (auto-created)"
echo "    - DATABASE_URL (add this, copy from POSTGRES_URL)"
echo "11. Click 'Deployments' → 'Redeploy'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2: Supabase (FREE Forever)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://supabase.com"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project'"
echo "4. Name: quizmaster"
echo "5. Create a strong database password (SAVE IT!)"
echo "6. Choose region closest to you"
echo "7. Wait 2 minutes for setup"
echo "8. Go to Settings → Database"
echo "9. Copy 'Connection string' (URI format)"
echo "10. Add ?sslmode=require at the end"
echo "11. Go to Vercel → Settings → Environment Variables"
echo "12. Add:"
echo "    Name: DATABASE_URL"
echo "    Value: postgresql://postgres:PASSWORD@db.xxx.supabase.co:5432/postgres?sslmode=require"
echo "13. Redeploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 3: Neon (FREE Tier)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://neon.tech"
echo "2. Sign up"
echo "3. Create new project: quizmaster"
echo "4. Copy the connection string"
echo "5. Add to Vercel environment variables"
echo "6. Redeploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "After Setting Up Database:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run migrations on your production database:"
echo ""
echo "  # Set the DATABASE_URL locally (copy from Vercel)"
echo "  export DATABASE_URL='your-production-database-url-here'"
echo ""
echo "  # Navigate to backend"
echo "  cd backend"
echo ""
echo "  # Run migrations"
echo "  python manage.py migrate --settings=config.settings.vercel"
echo ""
echo "  # Create admin user"
echo "  python manage.py createsuperuser --settings=config.settings.vercel"
echo ""
echo "  # Load sample data"
echo "  python manage.py create_sample_data --settings=config.settings.vercel"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test After Setup:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  python3 check_vercel_db.py"
echo ""
echo "Expected result: All tests should pass! ✅"
echo ""
echo "Then try registering from your frontend:"
echo "  https://quiz-master-app-roh5.vercel.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IMPORTANT: You MUST set up a database now!"
echo "    Your backend won't work without it."
echo ""
