#!/bin/bash

# Quiz Application - Development Environment Status
# This script shows the current status of all services

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     🎯 QUIZ APPLICATION - DEVELOPMENT ENVIRONMENT STATUS      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 SERVICE STATUS"
echo "─────────────────────────────────────────────────────────────────"
echo ""

# Check if backend is running
if curl -s http://localhost:8000/api/ > /dev/null 2>&1; then
    echo "✅ Backend (Django REST API)"
    echo "   URL: http://localhost:8000"
    echo "   Port: 8000"
    echo "   Database: SQLite (db.sqlite3)"
else
    echo "❌ Backend (Not Running)"
    echo "   To start: cd backend && python manage.py runserver 0.0.0.0:8000"
fi
echo ""

# Check if frontend is running
if curl -s http://localhost:3000/ > /dev/null 2>&1; then
    echo "✅ Frontend (React + Vite)"
    echo "   URL: http://localhost:3000"
    echo "   Port: 3000"
else
    echo "❌ Frontend (Not Running)"
    echo "   To start: cd frontend && npm run dev"
fi
echo ""

echo "📚 DOCUMENTATION & ADMIN"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "🔐 Admin Dashboard"
echo "   URL: http://localhost:8000/admin/"
echo "   Username: admin"
echo "   Password: admin123"
echo ""

echo "📖 API Documentation"
echo "   Swagger UI: http://localhost:8000/api/schema/swagger/"
echo "   ReDoc: http://localhost:8000/api/schema/redoc/"
echo ""

echo "🌐 MAIN ENDPOINTS"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Frontend"
echo "   http://localhost:3000/"
echo ""
echo "API Root"
echo "   http://localhost:8000/api/"
echo ""
echo "Users API"
echo "   http://localhost:8000/api/users/"
echo ""
echo "Quizzes API"
echo "   http://localhost:8000/api/quizzes/"
echo ""
echo "Results API"
echo "   http://localhost:8000/api/results/"
echo ""

echo "🛠️  TECHNOLOGY STACK"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Backend"
echo "   - Django 4.2.7"
echo "   - Django REST Framework 3.14.0"
echo "   - PostgreSQL (configured, using SQLite for dev)"
echo "   - Redis (configured for caching & Celery)"
echo "   - Celery (background tasks)"
echo ""
echo "Frontend"
echo "   - React 18.2.0"
echo "   - Vite 5.0.8"
echo "   - Tailwind CSS 3.4.1"
echo "   - Zustand 4.4.1"
echo "   - Framer Motion 10.16.4"
echo ""

echo "📋 QUICK COMMANDS"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Backend"
echo "   Start: cd backend && python manage.py runserver 0.0.0.0:8000"
echo "   Migrate: python manage.py migrate"
echo "   Shell: python manage.py shell"
echo "   Tests: pytest"
echo ""
echo "Frontend"
echo "   Start: cd frontend && npm run dev"
echo "   Build: npm run build"
echo "   Lint: npm run lint"
echo "   Format: npm run format"
echo ""

echo "🎯 NEXT STEPS"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "1. Create Quiz Data"
echo "   → Go to http://localhost:8000/admin/"
echo "   → Add Categories, Quizzes, and Questions"
echo ""
echo "2. Test the API"
echo "   → Go to http://localhost:8000/api/schema/swagger/"
echo "   → Try different endpoints"
echo ""
echo "3. Start Frontend Development"
echo "   → Build React components"
echo "   → Implement quiz UI"
echo ""

echo "✨ STATUS: READY FOR DEVELOPMENT"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Date: $(date '+%Y-%m-%d %H:%M:%S')"
echo "Environment: Development"
echo ""
echo "Happy coding! 🚀"
echo ""
