# Generated by Django 4.2.7 on 2025-11-09 19:26

import apps.live_quiz.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveQuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_code",
                    models.CharField(
                        default=apps.live_quiz.models.generate_join_code,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Players"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("allow_late_join", models.BooleanField(default=False)),
                ("show_leaderboard", models.BooleanField(default=True)),
                ("randomize_questions", models.BooleanField(default=False)),
                (
                    "time_per_question",
                    models.IntegerField(default=30, help_text="Seconds per question"),
                ),
                ("current_question_index", models.IntegerField(default=0)),
                (
                    "current_question_start_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_participants", models.IntegerField(default=0)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveQuizQuestionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_answers", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("wrong_count", models.IntegerField(default=0)),
                ("response_distribution", models.JSONField(default=dict)),
                ("average_time", models.FloatField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizzes.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_results",
                        to="live_quiz.livequizsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveQuizParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                            ("left", "Left"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                ("wrong_answers", models.IntegerField(default=0)),
                ("last_answer_time", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="live_quiz.livequizsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "last_answer_time"],
            },
        ),
        migrations.CreateModel(
            name="LiveQuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("answer_text", models.TextField(blank=True)),
                ("time_taken", models.FloatField(help_text="Seconds taken to answer")),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("points_awarded", models.IntegerField(default=0)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="live_quiz.livequizparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizzes.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quizzes.questionoption",
                    ),
                ),
            ],
            options={
                "ordering": ["answered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="livequizsession",
            index=models.Index(
                fields=["join_code"], name="live_quiz_l_join_co_d62c1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livequizsession",
            index=models.Index(
                fields=["status", "created_at"], name="live_quiz_l_status_f39e59_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="livequizquestionresult",
            unique_together={("session", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="livequizparticipant",
            unique_together={("session", "nickname"), ("session", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="livequizanswer",
            unique_together={("participant", "question")},
        ),
    ]
