"""Initial migration

Revision ID: d3559ab3efb7
Revises: 
Create Date: 2025-11-28 21:06:08.690333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3559ab3efb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_quizzes_category_id'), 'quizzes_category', ['id'], unique=False)
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users_user', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users_user', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_is_email_verified'), 'users_user', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_users_user_role'), 'users_user', ['role'], unique=False)
    op.create_index(op.f('ix_users_user_username'), 'users_user', ['username'], unique=True)
    op.create_table('quizzes_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('pass_percentage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True),
    sa.Column('shuffle_answers', sa.Boolean(), nullable=True),
    sa.Column('show_correct_answer', sa.Boolean(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('total_passes', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['quizzes_category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_quiz_id'), 'quizzes_quiz', ['id'], unique=False)
    op.create_table('results_userbadge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_userbadge_id'), 'results_userbadge', ['id'], unique=False)
    op.create_table('results_userstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_quizzes_taken', sa.Integer(), nullable=True),
    sa.Column('total_quizzes_passed', sa.Integer(), nullable=True),
    sa.Column('total_quizzes_failed', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('highest_score', sa.Float(), nullable=True),
    sa.Column('lowest_score', sa.Float(), nullable=True),
    sa.Column('total_time_spent', sa.Interval(), nullable=True),
    sa.Column('total_questions_attempted', sa.Integer(), nullable=True),
    sa.Column('total_questions_correct', sa.Integer(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('accuracy_rate', sa.Float(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_results_userstatistics_id'), 'results_userstatistics', ['id'], unique=False)
    op.create_table('users_emailverificationtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_users_emailverificationtoken_id'), 'users_emailverificationtoken', ['id'], unique=False)
    op.create_index(op.f('ix_users_emailverificationtoken_token'), 'users_emailverificationtoken', ['token'], unique=True)
    op.create_table('users_userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_users_userprofile_id'), 'users_userprofile', ['id'], unique=False)
    op.create_table('live_quiz_livequizsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('allow_late_join', sa.Boolean(), nullable=True),
    sa.Column('show_leaderboard', sa.Boolean(), nullable=True),
    sa.Column('randomize_questions', sa.Boolean(), nullable=True),
    sa.Column('time_per_question', sa.Integer(), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('current_question_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_participants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users_user.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes_quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_quiz_livequizsession_id'), 'live_quiz_livequizsession', ['id'], unique=False)
    op.create_index(op.f('ix_live_quiz_livequizsession_join_code'), 'live_quiz_livequizsession', ['join_code'], unique=True)
    op.create_table('quizzes_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes_quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_question_id'), 'quizzes_question', ['id'], unique=False)
    op.create_table('quizzes_quizattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes_quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_quizattempt_id'), 'quizzes_quizattempt', ['id'], unique=False)
    op.create_table('results_leaderboardentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('time_spent', sa.Interval(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('attempt_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes_quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_leaderboardentry_id'), 'results_leaderboardentry', ['id'], unique=False)
    op.create_table('live_quiz_livequizparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('wrong_answers', sa.Integer(), nullable=True),
    sa.Column('last_answer_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_quiz_livequizsession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_quiz_livequizparticipant_id'), 'live_quiz_livequizparticipant', ['id'], unique=False)
    op.create_table('live_quiz_livequizquestionresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('total_answers', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=True),
    sa.Column('response_distribution', sa.JSON(), nullable=True),
    sa.Column('average_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes_question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['live_quiz_livequizsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_quiz_livequizquestionresult_id'), 'live_quiz_livequizquestionresult', ['id'], unique=False)
    op.create_table('quizzes_questionoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_questionoption_id'), 'quizzes_questionoption', ['id'], unique=False)
    op.create_table('live_quiz_livequizanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['live_quiz_livequizparticipant.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes_question.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quizzes_questionoption.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_quiz_livequizanswer_id'), 'live_quiz_livequizanswer', ['id'], unique=False)
    op.create_table('quizzes_useranswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quizzes_quizattempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes_question.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quizzes_questionoption.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_useranswer_id'), 'quizzes_useranswer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_useranswer_id'), table_name='quizzes_useranswer')
    op.drop_table('quizzes_useranswer')
    op.drop_index(op.f('ix_live_quiz_livequizanswer_id'), table_name='live_quiz_livequizanswer')
    op.drop_table('live_quiz_livequizanswer')
    op.drop_index(op.f('ix_quizzes_questionoption_id'), table_name='quizzes_questionoption')
    op.drop_table('quizzes_questionoption')
    op.drop_index(op.f('ix_live_quiz_livequizquestionresult_id'), table_name='live_quiz_livequizquestionresult')
    op.drop_table('live_quiz_livequizquestionresult')
    op.drop_index(op.f('ix_live_quiz_livequizparticipant_id'), table_name='live_quiz_livequizparticipant')
    op.drop_table('live_quiz_livequizparticipant')
    op.drop_index(op.f('ix_results_leaderboardentry_id'), table_name='results_leaderboardentry')
    op.drop_table('results_leaderboardentry')
    op.drop_index(op.f('ix_quizzes_quizattempt_id'), table_name='quizzes_quizattempt')
    op.drop_table('quizzes_quizattempt')
    op.drop_index(op.f('ix_quizzes_question_id'), table_name='quizzes_question')
    op.drop_table('quizzes_question')
    op.drop_index(op.f('ix_live_quiz_livequizsession_join_code'), table_name='live_quiz_livequizsession')
    op.drop_index(op.f('ix_live_quiz_livequizsession_id'), table_name='live_quiz_livequizsession')
    op.drop_table('live_quiz_livequizsession')
    op.drop_index(op.f('ix_users_userprofile_id'), table_name='users_userprofile')
    op.drop_table('users_userprofile')
    op.drop_index(op.f('ix_users_emailverificationtoken_token'), table_name='users_emailverificationtoken')
    op.drop_index(op.f('ix_users_emailverificationtoken_id'), table_name='users_emailverificationtoken')
    op.drop_table('users_emailverificationtoken')
    op.drop_index(op.f('ix_results_userstatistics_id'), table_name='results_userstatistics')
    op.drop_table('results_userstatistics')
    op.drop_index(op.f('ix_results_userbadge_id'), table_name='results_userbadge')
    op.drop_table('results_userbadge')
    op.drop_index(op.f('ix_quizzes_quiz_id'), table_name='quizzes_quiz')
    op.drop_table('quizzes_quiz')
    op.drop_index(op.f('ix_users_user_username'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_role'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_is_email_verified'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_id'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_email'), table_name='users_user')
    op.drop_table('users_user')
    op.drop_index(op.f('ix_quizzes_category_id'), table_name='quizzes_category')
    op.drop_table('quizzes_category')
    # ### end Alembic commands ###
